### ISSUE TITLE
Suggestion: Adding an working example would be highly helpful. 

### ISSUE THREAD

**Issue by satyagupta** [nimaltd/w25qxx#10]
Thank you very much for helpful library, but for a beginners like me an working example would be very helpful to understand how it works. 

Like the SPI.h file which needs to be replaced with the correct SPI header, i found this after trying many things and still i cant get it to work. 

I am sure i am missing few things here and there but since i am a beginner an example would help a lot :)

**Comment by nimaltd** [comment]
Hello. Spi.h generate by cubemx. Please read readme file. You can enable to generate spi.h

**Comment by satyagupta** [comment]
I am sorry but i could find anything related to generating SPI.h file. 

The readme file just have following lines

```
1. Enable SPI and a Gpio as output(CS pin).Connect WP and HOLD to VCC. ( done in CubeMX and passed the SPI object in conf.h)
2. Select General peripheral Initalizion as a pair of '.c/.h' file per peripheral on project settings. ( i hope you mean to add the files in the program)
3. Config w25qxxConf.h. (done)
4. Call W25qxx_Init(). (done)
5. After init, you can watch w25qxx struct.(Chip ID,page size,sector size and ...) (ok)
6. In Read/Write Function, you can put 0 to NumByteToRead/NumByteToWrite parameter to maximum. (ok)
7. Dont forget to erase page/sector/block before write. (ok)
```


Above are the lines that i see in read me, nothing else. Am i missing anything?

**Comment by nimaltd** [comment]
Line 2

**Comment by satyagupta** [comment]
I was not able to get it work as per your instructions but i figure that it need the SPI handler to work. I added some work around as per my understand and made it to work. Thanks for your quick reply, i really appreciate it :)

I would once again request if you can please consider adding a small example.

**Comment by nimaltd** [comment]
I dont have any example yet.

**Comment by nimaltd** [comment]
If you enabled that setting  on cubemx . Spi handler generated correctly

**Comment by satyagupta** [comment]
That's what confusing me. Which settings? Can you share screenshot of the
same please? If u can?

**Comment by nimaltd** [comment]
I dont have pc now. 
Project manager...code genaration

**Comment by satyagupta** [comment]
Found it, thanks
