### ISSUE TITLE
Library don't work

### ISSUE THREAD

**Issue by in-text** [nimaltd/w25qxx#13]
Hello! I wanted to use this library to create the Mass Storage Device, but when I insert all the necessary functions (initialization, reading, writing, erasing) the device is not recognized on the PC - the functions simply are not executed. I turned off the use of freeTROS and debug mode, and yet nothing works and the functions are not performed. With what it can be connected?
I use stm32f103c8, flash-chip is W25Q64
Thanks for the help!

**Comment by in-text** [comment]
The usbd_storage_if.c file looks like this:
`#include <usbd_def.h>
#include <usbd_msc_scsi.h>
#include <w25qxx.h>
#include "usbd_storage_if.h"
#include <w25qxxConf.h>

#define STORAGE_BLK_NBR      0x800
#define STORAGE_BLK_SIZ        0x1000

int8_t STORAGE_Init_FS(uint8_t lun)
{
	W25qxx_Init();
  return (USBD_OK);
}

int8_t STORAGE_Read_FS(uint8_t lun, uint8_t *buf, uint32_t blk_addr, uint16_t blk_len)
{
	W25qxx_ReadSector(buf,blk_addr,0,0);
	return (USBD_OK);
}

int8_t STORAGE_Write_FS(uint8_t lun, uint8_t *buf, uint32_t blk_addr, uint16_t blk_len)
{
	W25qxx_EraseSector(blk_addr);
	W25qxx_WriteSector(buf,blk_addr,0, 0);
  return (USBD_OK);
}`

The size of one media package - 4096  bytes

**Comment by nimaltd** [comment]
Hello. Test library without mass storage class.
Its worked fine
