### ISSUE TITLE
Can i get a full example of it?

### ISSUE THREAD

**Issue by albertomercurio** [nimaltd/w25qxx#14]
Hello,
I need to configure with Quad SPI my W25Q256JVEIQ chip.
I read the readme and i think i understood all of it. However, i don't know where to insert the `W25qxx_Init()` function, i think after the general initialization like
```
static void MX_QUADSPI_Init(void)
{

  /* USER CODE BEGIN QUADSPI_Init 0 */

  /* USER CODE END QUADSPI_Init 0 */

  /* USER CODE BEGIN QUADSPI_Init 1 */

  /* USER CODE END QUADSPI_Init 1 */
  /* QUADSPI parameter configuration*/
  hqspi.Instance = QUADSPI;
  hqspi.Init.ClockPrescaler = 255;
  hqspi.Init.FifoThreshold = 1;
  hqspi.Init.SampleShifting = QSPI_SAMPLE_SHIFTING_NONE;
  hqspi.Init.FlashSize = 1;
  hqspi.Init.ChipSelectHighTime = QSPI_CS_HIGH_TIME_1_CYCLE;
  hqspi.Init.ClockMode = QSPI_CLOCK_MODE_0;
  hqspi.Init.FlashID = QSPI_FLASH_ID_1;
  hqspi.Init.DualFlash = QSPI_DUALFLASH_DISABLE;
  if (HAL_QSPI_Init(&hqspi) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN QUADSPI_Init 2 */
  W25qxx_Init();
  /* USER CODE END QUADSPI_Init 2 */

}
```

but, as you can see i don't know the right parameters to put in this initial configuration.
I need to use it for touchgfx external flash. Is this initialization sufficient for this purpose?

**Comment by nimaltd** [comment]
Hello  this library does not support quadspi.

**Comment by albertomercurio** [comment]
Is there some way to convert this for Quad SPI?

**Comment by nimaltd** [comment]
Diffrent in init . Wspi Use another address and in transfer. It may be support in future.
