### ISSUE TITLE
WriteBytes

### ISSUE THREAD

**Issue by Lucy2003** [nimaltd/w25qxx#17]
There is no Function to Write Bytes.It just WriteByte.

If using For(){} , it's too slow.

Could you please  add a function 
void W25qxx_WriteBytes(uint8_t *pBuffer, uint32_t WriteAddr_inBytes,uint32_t NumByteToWrite); 

Thank you!

**Comment by AlexKeisy** [comment]
I have that function, tested. work fine.

But i dont know how to share

2020-07-06 9:32 GMT+05:00, Lucy2003 <notifications@github.com>:

**Comment by Lucy2003** [comment]
> I have that function, tested. work fine. But i dont know how to share 2020-07-06 9:32 GMT+05:00, Lucy2003 <notifications@github.com>:
> […](#)
> There is no Function to Write Bytes.It just WriteByte. If using For(){} , it's too slow. Could you please add a function void W25qxx_WriteBytes(uint8_t *pBuffer, uint32_t WriteAddr_inBytes,uint32_t NumByteToRead); Thank you! -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #17

Could you please comment here?Just using "Insect Code" on the comment bar

**Comment by AlexKeisy** [comment]
//###################################################################################################################
// RetVal number of written bytes
uint32_t W25qxx_WriteBytes(uint8_t* pBuffer, uint32_t writeAddr,
uint32_t NumByteToWrite){
	uint32_t CurrAddr, PosInPage, BytesToWriteInCurrPage, RemBytesToWrite;
	while(w25qxx.Lock==1)
		W25qxx_Delay(1);
	w25qxx.Lock=1;
	#if (_W25QXX_DEBUG==1)
	uint32_t	StartTime=HAL_GetTick();
	printf("w25qxx N=%d WriteBytes  at address %d
begin...",(int)NumByteToWrite,(int)writeAddr);
	#endif
	//Check for flash size
	if ((w25qxx.CapacityInKiloByte*1024)<(writeAddr+NumByteToWrite))
{	return 0; }//!!! error return 0 bytes written

	RemBytesToWrite=NumByteToWrite;// remaining bytes to write
	CurrAddr = writeAddr ;
	PosInPage = writeAddr % w25qxx.PageSize; //The first page may be not
aligned to page
	while (RemBytesToWrite>0)
	{	// how many bytes to write in current  page
		BytesToWriteInCurrPage = (RemBytesToWrite > (w25qxx.PageSize -
PosInPage))? (w25qxx.PageSize - PosInPage): RemBytesToWrite;
		W25qxx_WaitForWriteEnd();// waiting for previous operation
		W25qxx_WriteEnable();
		HAL_GPIO_WritePin(_W25QXX_CS_GPIO,_W25QXX_CS_PIN,GPIO_PIN_RESET);
		W25qxx_SpiTx(0x02);//!!!constant in code
		if(w25qxx.ID>=W25Q256)	W25qxx_SpiTx((CurrAddr & 0xFF000000) >>
24);// 32 bit address
		W25qxx_SpiTx((CurrAddr & 0xFF0000) >> 16);
		W25qxx_SpiTx((CurrAddr & 0xFF00) >> 8);
		W25qxx_SpiTx(CurrAddr & 0xFF);
		if (W25qxx_SPI_Transmit(&_W25QXX_SPI,pBuffer,BytesToWriteInCurrPage,100)!=HAL_OK)
		{
			HAL_GPIO_WritePin(_W25QXX_CS_GPIO,_W25QXX_CS_PIN,GPIO_PIN_SET);
			break;
		}
		HAL_GPIO_WritePin(_W25QXX_CS_GPIO,_W25QXX_CS_PIN,GPIO_PIN_SET);
		RemBytesToWrite -= BytesToWriteInCurrPage;
		CurrAddr +=BytesToWriteInCurrPage;
		pBuffer  +=BytesToWriteInCurrPage;
		PosInPage=0;
	}
	W25qxx_WaitForWriteEnd();// waiting for the end of any operation
	w25qxx.Lock=0;
	#if (_W25QXX_DEBUG==1)
		printf("w25qxx WriteBytes  done for %d ms., written %d bytes  of %d
\r\n",(int)(HAL_GetTick()-StartTime),(int)(NumByteToWrite-RemBytesToWrite),(int)NumByteToWrite);
	#endif
	return  NumByteToWrite-RemBytesToWrite;
}

2020-07-06 10:15 GMT+05:00, Lucy2003 <notifications@github.com>:

**Comment by Lucy2003** [comment]
Think you.
