### ISSUE TITLE
How to read and write structs

### ISSUE THREAD

**Issue by satyagupta** [nimaltd/w25qxx#18]
This is a fantastic library, but as i had mentioned earlier "It lacks a working example" 

I want to use this library to write and read content in pages.

I have structs (they are less than 256 byes in size) i want to write and read them.

How do you suggest to do the same? 

I am using 0 as starting address for the page and for every page i increment it by 100(hexa) for the next address. 

`uint32_t base_address = 0x00000000;`
`uint32_t page_offset = 0x100;`

`W25qxx_WritePage( (uint8_t *) &c, base_address + ( page_offset*0 ), 0, sizeof(c)); HAL_Delay(100);`
`W25qxx_ReadPage( (uint8_t *) &c, base_address + ( page_offset*0 ), 0, sizeof(c));`

**Comment by nimaltd** [comment]
You can watch your maximum page address in debug(w25qxx struct) 
You must increase page one by one. Not 0x100.
One page contain 256 bytes.

**Comment by satyagupta** [comment]
Yea i know that, 256 (decimal) = 100( hexa)

But thats irrelevant. The address is working just fine but any variable in struct which is longer than byte (word or half word) is not getting written correctly in the flash.

**Comment by satyagupta** [comment]
Can you please explain me one thing. 
What will happen with the following functions?

`W25qxx_ReadPage( (uint8_t *) &c, 0x00010000, 0, sizeof(c));`
`W25qxx_ReadPage( (uint8_t *) &calib_clone, 0x00010100, 0 , sizeof(calib_clone)); `

**Comment by satyagupta** [comment]
I have figured out a work around to write struct which works fine. 

I am facing different issue or may be its wrong method that i am implying. 

Do we have to erase data  before writing content over it? is this correct?

Because if i write data over previously written content its not correct. Something always gets messed up. But if i erase the whole chip and write again it works just fine.

**Comment by nimaltd** [comment]
Yes. You must erase before write

**Comment by satyagupta** [comment]
How do we do that? The only option is to erase Block, Sector or whole chip

How do you suggest we do it with page?

**Comment by nimaltd** [comment]
The only one page can not erase.

**Comment by satyagupta** [comment]
What do you suggest advice?

**Comment by satyagupta** [comment]
Figured out that its better to write in sectors than pages. And solved the issues. 

Closing this issue. Thanks for your help :)
