### ISSUE TITLE
HAL_GetTick() Should not be used

### ISSUE THREAD

**Issue by zhaonianzhu** [nimaltd/w25qxx#22]
bool	W25qxx_Init(void)
{
	w25qxx.Lock=1;	
	while(HAL_GetTick()<100)//here  ,i maybe use other os 
    W25qxx_Delay(1);
after：
W25qxx_Delay(100);
is good！

**Comment by nimaltd** [comment]
w25q need some delay after power up to work.

**Comment by zhaonianzhu** [comment]
Each RTOS has a different delay function, `#define W25qxx_Delay os_delay`is better
