### ISSUE TITLE
check the status of every HAL_SPI_ call

### ISSUE THREAD

**Issue by NatiUnger** [nimaltd/w25qxx#42]
Hi,
First thanks for the drivers, I didnt check them yet by hardware, but i want to suggest some things:
1. All the HAL_SPI_ calls has return of success\fail status, it's important to verify them.
2. If there is RTOS, it's better to use mutex.
What do you think about it?

**Comment by nimaltd** [comment]
Hello. I am working on a new library that can integrated in CubeMx platform. Please Wait for the new one. Thanks
