### ISSUE TITLE
Cannot install from CubeMx, shows "The specified URL is invalid"

### ISSUE THREAD

**Issue by Scarittagle** [nimaltd/w25qxx#49]
I tried to install it through CubeMX's Embedded Software Packages Manager,

When I entered the URL in User Defined Packs Manager, it shows "The specified URL is invalid".

Is there another way to install the library?

CubeMX version: 6.9.2

![image](https://github.com/user-attachments/assets/c78118eb-54d0-4c50-9d69-1c86240c80ff)

**Comment by nimaltd** [comment]
Please update the cubemx

**Comment by Scarittagle** [comment]
Hi [nimaltd](https://github.com/nimaltd),

I updated the CubeMX to 6.12.1 and it is still giving me this error.

**Comment by nimaltd** [comment]
Hi, please try 
https://github.com/nimaltd/STM32-PACK/raw/main/NimaLTD.pidx

**Comment by Scarittagle** [comment]
Hi nimaltd,

how about manual install?

![image](https://github.com/user-attachments/assets/5ae4b676-dbdd-497c-94ee-99276de75f63)

**Comment by nimaltd** [comment]
Hi. For sure you can manual install.
Download it and install it
