### ISSUE TITLE
How Can You Calculate Block Count Variable ? 

### ISSUE THREAD

**Issue by volkanunal** [nimaltd/w25qxx#5]
Hi ,
 
First of all thanks for lib.

i want to learn something about your calculation method.  According to your library ,  for W25M12 flash ,  (https://www.winbond.com/resource-files/w25n01gv%20revg%20032116.pdf) . How can you calculate block count as 1024 ? 

Best Regards , 
Volkan

**Comment by nimaltd** [comment]
Hello. your welcome.
your flash is different. Maximum in my library is w25q512. you can read datasheet an add your flash config in init function. (page 16)
